<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CheckIfAtFloor" Id="{d18c60a8-2a65-41b2-8bfe-01227aff4eea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CheckIfAtFloor : BOOL
VAR_INPUT
	
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CheckIfAtFloor">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>