<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Floor2" Id="{1b66c6d5-e132-4dd6-bb1d-63572541cf58}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Floor2
VAR
	floorTwoLamp : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Floor2">
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>